-- MySQL Script generated by MySQL Workbench
-- Mon May 31 14:30:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`matakuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`matakuliah` (
  `idmatakuliah` INT NOT NULL AUTO_INCREMENT,
  `nama_matkul` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmatakuliah`),
  UNIQUE INDEX `idmatakuliah_UNIQUE` (`idmatakuliah` ASC) VISIBLE,
  UNIQUE INDEX `nama_matkul_UNIQUE` (`nama_matkul` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 202
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`semester` (
  `idsemester` INT NOT NULL AUTO_INCREMENT,
  `tipe` VARCHAR(45) NOT NULL,
  `tahun` INT NOT NULL,
  UNIQUE INDEX `idsemester_UNIQUE` (`idsemester` ASC) VISIBLE,
  PRIMARY KEY (`idsemester`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`semesterf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`semesterf` (
  `idsemesterF` INT NOT NULL AUTO_INCREMENT,
  `semester` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsemesterF`),
  UNIQUE INDEX `semester_UNIQUE` (`semester` ASC) VISIBLE,
  CONSTRAINT `idsemester`
    FOREIGN KEY (`idsemesterF`)
    REFERENCES `test`.`semester` (`idsemester`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`tests` (
  `idtests` INT NOT NULL AUTO_INCREMENT,
  `nama_test` VARCHAR(45) NOT NULL,
  `id_semester` INT NOT NULL,
  `id_matkul` INT NOT NULL,
  `waktu` INT NOT NULL,
  PRIMARY KEY (`idtests`),
  UNIQUE INDEX `idtests_UNIQUE` (`idtests` ASC) VISIBLE,
  UNIQUE INDEX `nama_test_UNIQUE` (`nama_test` ASC) VISIBLE,
  INDEX `semester_idx` (`id_semester` ASC) VISIBLE,
  INDEX `matkul_idx` (`id_matkul` ASC) VISIBLE,
  CONSTRAINT `matkul`
    FOREIGN KEY (`id_matkul`)
    REFERENCES `test`.`matakuliah` (`idmatakuliah`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `semester`
    FOREIGN KEY (`id_semester`)
    REFERENCES `test`.`semesterf` (`idsemesterF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 307
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`soal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`soal` (
  `idsoal` INT NOT NULL AUTO_INCREMENT,
  `soal` LONGTEXT NOT NULL,
  `tipe` VARCHAR(45) NOT NULL,
  `test` INT NOT NULL,
  PRIMARY KEY (`idsoal`),
  INDEX `test_idx` (`test` ASC) VISIBLE,
  CONSTRAINT `test`
    FOREIGN KEY (`test`)
    REFERENCES `test`.`tests` (`idtests`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 402
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `test`.`jawabpg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`jawabpg` (
  `idjawabpg` INT NOT NULL AUTO_INCREMENT,
  `soal` INT NOT NULL,
  `jawab` LONGTEXT NOT NULL,
  `benar` TINYINT(3) UNSIGNED ZEROFILL NOT NULL DEFAULT '000',
  PRIMARY KEY (`idjawabpg`),
  INDEX `soal_idx` (`soal` ASC) VISIBLE,
  CONSTRAINT `soal`
    FOREIGN KEY (`soal`)
    REFERENCES `test`.`soal` (`idsoal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 503
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
